import{a as L,S as w,i as a}from"./assets/vendor-5YrzWRhu.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))s(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const i of o.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&s(i)}).observe(document,{childList:!0,subtree:!0});function n(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function s(e){if(e.ep)return;e.ep=!0;const o=n(e);fetch(e.href,o)}})();const S="https://pixabay.com/api/",v="51594808-2f8a269bf80026fef40a32938";async function q(r,t=1){const n={key:v,q:r,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:15,page:t};return(await L.get(S,{params:n})).data}const y=document.querySelector(".gallery"),p=document.querySelector(".load-more-btn"),m=document.querySelector(".loader"),P=new w(".gallery a");function $(r){const t=r.map(({webformatURL:n,largeImageURL:s,tags:e,likes:o,views:i,comments:h,downloads:b})=>`
    <li class="gallery-item">
      <a href="${s}">
        <img src="${n}" alt="${e}" loading="lazy" />
      </a>
      <div class="info">
        <p><b>Likes:</b> ${o}</p>
        <p><b>Views:</b> ${i}</p>
        <p><b>Comments:</b> ${h}</p>
        <p><b>Downloads:</b> ${b}</p>
      </div>
    </li>`).join("");y.insertAdjacentHTML("beforeend",t),P.refresh()}function B(){y.innerHTML=""}function M(){m.style.display="block"}function R(){m.style.display="none"}function E(){p.style.display="block"}function u(){p.style.display="none"}const c=document.querySelector(".form"),O=document.querySelector(".load-more-btn");let d="",l=1,f=0;c.addEventListener("submit",async r=>{if(r.preventDefault(),d=c.elements["search-text"].value.trim(),!d){a.warning({title:"Warning",message:"Please enter a search term",position:"topRight"});return}l=1,B(),u(),await g(),c.reset()});O.addEventListener("click",async()=>{l+=1,await g(!0)});async function g(r=!1){M();try{const t=await q(d,l),{hits:n,totalHits:s}=t;if(f=s,n.length===0){a.info({title:"No results",message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"}),u();return}$(n),l*15<f?E():(u(),a.info({title:"End of results",message:"We're sorry, but you've reached the end of search results.",position:"topRight"})),r&&x()}catch(t){console.error(t),a.error({title:"Error",message:"Something went wrong. Try again later.",position:"topRight"})}finally{R()}}function x(){const r=document.querySelector(".gallery .gallery-item");if(!r)return;const{height:t}=r.getBoundingClientRect();window.scrollBy({top:2*t,behavior:"smooth"})}
//# sourceMappingURL=index.js.map
